---
title: "Overview"
subtitle: "The logic of hypothesis testing and confidence intervals"
toc: true
toc-location: right
editor: 
  markdown: 
    wrap: 72
---

This week, we dive into the core logic of hypothesis testing. You will
learn to navigate the risks of Type I and Type II errors and understand
the mechanics behind the sampling distribution of the mean. Finally, we
will apply these concepts to calculate standard error and build
confidence intervals

![Artwork by @allison_horst: "type 1
error"](images/type-1-error.png){fig-alt="A cute population with a normal distribution with two samples, one which happens to have at mean at the low end of the population and one at the high end. The population is saying 'yes, I'm still sure I birthed both you'. Because these samples are relatively rare - would happen less than 5% of the time - we would conclude they did not come from this population. That would be making a type 1 error."
width="800"}

![Artwork by @allison_horst: "type 2
error"](images/type-2-error.png){fig-alt="Two cute populations with a normal distribution with very little overlap. There are two samples, one which happens to have at mean at the low end of one population and and the other at the high end of the other population so that the two samples are close togther. Deciding these two samples were from the same population would be making a type 2 error."
width="600"}

### Learning objectives

The successful student will be able to:

-   demonstrate the process of hypothesis testing with an example

-   explain type 1 and type 2 errors

-   define the sampling distribution of the mean and the standard error

-   explain what a confidence interval is

-   calculate confidence intervals for large and small samples

### Instructions

1.  [Prepare](study_before_workshop.qmd)

    i.  📖 Read The logic of hyothesis testing
    ii. 📖 Read Confidence Intervals

2.  [Workshop](workshop.qmd)

    i.  💻 Remind yourself how to import files
    ii. 💻 Calculate confidence intervals on large
    iii. 💻 Calculate confidence intervals on small samples.

3.  [Consolidate](study_after_workshop.qmd)

    i.  💻 Calculate confidence intervals for each group in a data set
