---
title: "Overview"
subtitle: "Assessment introduction"
toc: true
toc-location: right

---

This week we will be looking at the assessment for this module and introducing you to a specimen sample of the assessment so that you can familiarise yourself with the format and what we are expecting you to produce. We will be looking at a Rproject containing a quarto markdown file and a report results section. We will also look at the marking criteria. This material can also be found on the VLE under the module assessment marking criteria section. Next week we will cover how to reproduce a quarto markdown file yourself in more detail.

### Learning objectives

The successful student will be able to:

- Understand the structure of the Rproject we will be expecting you to produce in the assessment (e.g. segregated into data-raw, figures etc).

- Understand the marking criteria so you understand how the assessment is going to be evaluated e.g. one aspect we will be looking at is whether the code within the quarto markdown generates the plots included within the report.

- Know where to look on the VLE for additional assessment information

- Know the appropriate dates for the release and submisison of the assessment.



### Instructions

1.  [Prepare](study_before_workshop.qmd)

    i.  📖 Read the marking criteria available on the VLE


2.  [Workshop](workshop.qmd)

    i. 💻 Explore the specimen Rproject

3.  [Consolidate](study_after_workshop.qmd)

    i.  📖 Refamiliarise yourself with how Rprojects work
