---
title: "Independent Study - after the workshop"
format:
  html:
    code-fold: true
    code-summary: "Answer - don't look until you have tried!"
---

# Set up

If you have just opened RStudio you will want to load the packages and import the data.

```{r}
#| code-fold: false
library(tidyverse)
library(readxl)
```


1.  💻 Summarise and plot the `pigeons` dataframe appropriately.

```{r}
#| code-fold: true

# import
pigeons <- read_table("data-raw/pigeon.txt")

# reformat to tidy
pigeons <- pivot_longer(data = pigeons, 
                        cols = everything(), 
                        names_to = "population", 
                        values_to = "distance")

# sumnmarise
pigeons_summary <- pigeons %>%
  group_by(population) %>%
  summarise(mean = mean(distance),
            std = sd(distance),
            n = length(distance),
            se = std/sqrt(n))
# plot
ggplot() +
  geom_point(data = pigeons, aes(x = population, y = distance),
             position = position_jitter(width = 0.1, height = 0),
             colour = "gray50") +
  geom_errorbar(data = pigeons_summary, 
                aes(x = population, ymin = mean - se, ymax = mean + se),
                width = 0.3) +
  geom_errorbar(data = pigeons_summary, 
                aes(x = population, ymin = mean, ymax = mean),
                width = 0.2) +
  scale_y_continuous(name = "Interorbital distance (mm)", 
                     limits = c(0, 14), 
                     expand = c(0, 0)) +
  scale_x_discrete(name = "Population") +
  theme_classic()

```
The data in x are a blood data contain x variable

2. 💻 Make a new project
3. 💻 Make folders for data and for figures
4. 💻 Import the data
5. 💻 Summarise and plot variables of your choice