project:
  type: website
  output-dir: _site

website:
  title: "Data Analysis in R "
  navbar:
    background: light
    twitter-card: true
    site-url: https://3mmarand.github.io/R4BABS/
    repo-url: https://github.com/3mmaRand/R4BABS
    issue-url: https://github.com/3mmaRand/R4BABS/issues/new/choose
    repo-actions: [edit, issue]
    page-navigation: true
    search: true
    page-footer:
      center: '`r paste("Please cite as: ", cffr::cff_to_bibtex("CITATION.cff"))`'
    left:
      - text: "Welcome!"
        file: index.qmd
      - text: "BABS 1"
        file:  r4babs1/r4babs1.qmd
      - text: "BABS 2"
        file:  r4babs2/r4babs2.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/er_13
        text: Emma's Twitter
      - icon: github
        href: https://github.com/3mmaRand/R4BABS
        text: R4BABS on GitHub

  sidebar:
    - title: "BABS 1"
      style: "floating"
      background: light
      contents:
          - href: r4babs1/r4babs1.qmd
            text: Overview
          - section: "Week 6"
            contents: 
             - href: r4babs1/week-6/overview.qmd
               text: About  
             - href: r4babs1/week-6/study_before_workshop.qmd
               text: Prepare! 
             - href: r4babs1/week-6/workshop.qmd
               text: Workshop
             - href: r4babs1/week-6/study_after_workshop.qmd
               text: Consolidate!  
          - section: "Week 7"
            contents: 
             - href: r4babs1/week-7/overview.qmd
               text: About  
             - href: r4babs1/week-7/study_before_workshop.qmd
               text: Prepare! 
             - href: r4babs1/week-7/workshop.qmd
               text: Workshop
             - href: r4babs1/week-7/study_after_workshop.qmd
               text: Consolidate!  
          - section: "Week 8"
            contents: 
             - href: r4babs1/week-8/overview.qmd
               text: About  
             - href: r4babs1/week-8/study_before_workshop.qmd
               text: Prepare! 
             - href: r4babs1/week-8/workshop.qmd
               text: Workshop
             - href: r4babs1/week-8/study_after_workshop.qmd
               text: Consolidate!  
          - section: "Week 9"
            contents: 
             - href: r4babs1/week-9/overview.qmd
               text: About  
             - href: r4babs1/week-9/study_before_workshop.qmd
               text: Prepare! 
             - href: r4babs1/week-9/workshop.qmd
               text: Workshop
             - href: r4babs1/week-9/study_after_workshop.qmd
               text: Consolidate!  
    - title: "BABS 2"
      style: "floating"
      background: light
      contents: 
          - href: r4babs2/r4babs2.qmd
            text: Overview
          - section: "Week 6"
            contents: 
             - href: r4babs1/week-6/overview.qmd
               text: About  
             - href: r4babs1/week-6/study_before_workshop.qmd
               text: Prepare! 
             - href: r4babs1/week-6/workshop.qmd
               text: Workshop
             - href: r4babs1/week-6/study_after_workshop.qmd
               text: Consolidate!  
          - section: "Week 7"
            contents: 
             - href: r4babs1/week-7/overview.qmd
               text: About  
             - href: r4babs1/week-7/study_before_workshop.qmd
               text: Prepare! 
             - href: r4babs1/week-7/workshop.qmd
               text: Workshop
             - href: r4babs1/week-7/study_after_workshop.qmd
               text: Consolidate!  
          - section: "Week 8"
            contents: 
             - href: r4babs1/week-8/overview.qmd
               text: About  
             - href: r4babs1/week-8/study_before_workshop.qmd
               text: Prepare! 
             - href: r4babs1/week-8/workshop.qmd
               text: Workshop
             - href: r4babs1/week-8/study_after_workshop.qmd
               text: Consolidate!  
          - section: "Week 9"
            contents: 
             - href: r4babs1/week-9/overview.qmd
               text: About  
             - href: r4babs1/week-9/study_before_workshop.qmd
               text: Prepare! 
             - href: r4babs1/week-9/workshop.qmd
               text: Workshop
             - href: r4babs1/week-9/study_after_workshop.qmd
               text: Consolidate!  

execute:
  echo: true
  warning: false
  output: true
  error: true

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-link: true
    code-overflow: wrap
    code-line-numbers: false

bibliography: references.bib


editor: visual

