project:
  type: website
  output-dir: _site

website:
  title: "Data Analysis in R "
  page-footer:
    left: "`r cffr::cff_to_bibtex('CITATION.cff')`"
    right:
      - icon: twitter
        href: https://twitter.com/er_13
        aria-label: Twitter
      - icon: github
        href: https://github.com/3mmaRand/R4BABS
        aria-label: R4BABS GitHub
  navbar:
    background: light
    twitter-card: true
    site-url: https://3mmarand.github.io/R4BABS/
    repo-url: https://github.com/3mmaRand/R4BABS
    issue-url: https://github.com/3mmaRand/R4BABS/issues/new/choose
    repo-actions: [edit, issue]
    page-navigation: true
    search: true
    left:
      - text: "Welcome!"
        file: index.qmd
      - text: "BABS 1"
        file:  r4babs1/r4babs1.qmd
      - text: "BABS 2"
        file:  r4babs2/r4babs2.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/er_13
        text: Emma's Twitter
      - icon: github
        href: https://github.com/3mmaRand/R4BABS
        text: R4BABS GitHub

  sidebar:
    - title: "BABS 1"
      style: "floating"
      background: primary
      contents:
          - href: r4babs1/r4babs1.qmd
          - text: ---
          - text: ---
          - section: "Week 6: Understanding file systems"
            contents: 
             - href: r4babs1/week-6/overview.qmd
               text: About  
             - href: r4babs1/week-6/study_before_workshop.qmd
               text: Prepare! 
             - href: r4babs1/week-6/workshop.qmd
               text: Workshop
             - href: r4babs1/week-6/study_after_workshop.qmd
               text: Consolidate!  
          - text: ---
          - section: "Week 7: Introduction to R, RStudio and project organisation"
            contents: 
             - href: r4babs1/week-7/overview.qmd
               text: About  
             - href: r4babs1/week-7/study_before_workshop.qmd
               text: Prepare! 
             - href: r4babs1/week-7/workshop.qmd
               text: Workshop
             - href: r4babs1/week-7/study_after_workshop.qmd
               text: Consolidate!  
          - text: ---
          - section: "Week 8: Types of variable, the normal distribution and summarising data"
            contents: 
             - href: r4babs1/week-8/overview.qmd
               text: About  
             - href: r4babs1/week-8/study_before_workshop.qmd
               text: Prepare! 
             - href: r4babs1/week-8/workshop.qmd
               text: Workshop
             - href: r4babs1/week-8/study_after_workshop.qmd
               text: Consolidate!  
          - text: ---
          - section: "Week 9: Summarising data in with several variables and the role of variables in analysis"
            contents: 
             - href: r4babs1/week-9/overview.qmd
               text: About  
             - href: r4babs1/week-9/study_before_workshop.qmd
               text: Prepare! 
             - href: r4babs1/week-9/workshop.qmd
               text: Workshop
             - href: r4babs1/week-9/study_after_workshop.qmd
               text: Consolidate!  
    - title: "BABS 2"
      style: "floating"
      background: secondary
      contents: 
          - href: r4babs2/r4babs2.qmd
          - text: ---
          - text: ---
          - section: "Week 1"
            contents: 
             - href: r4babs2/week-1/overview.qmd
               text: About  
             - href: r4babs2/week-1/study_before_workshop.qmd
               text: Prepare! 
             - href: r4babs2/week-1/workshop.qmd
               text: Workshop
             - href: r4babs2/week-1/study_after_workshop.qmd
               text: Consolidate!  
          - text: ---
          - section: "Week 2"
            contents: 
             - href: r4babs2/week-2/overview.qmd
               text: About  
             - href: r4babs2/week-2/study_before_workshop.qmd
               text: Prepare! 
             - href: r4babs2/week-2/workshop.qmd
               text: Workshop
             - href: r4babs2/week-2/study_after_workshop.qmd
               text: Consolidate!  
          - text: ---
          - section: "Week 3"
            contents: 
             - href: r4babs2/week-3/overview.qmd
               text: About  
             - href: r4babs2/week-3/study_before_workshop.qmd
               text: Prepare! 
             - href: r4babs2/week-3/workshop.qmd
               text: Workshop
             - href: r4babs2/week-3/study_after_workshop.qmd
               text: Consolidate!  
          - text: ---
          - section: "Week 4"
            contents: 
             - href: r4babs2/week-4/overview.qmd
               text: About  
             - href: r4babs2/week-4/study_before_workshop.qmd
               text: Prepare! 
             - href: r4babs2/week-4/workshop.qmd
               text: Workshop
             - href: r4babs2/week-4/study_after_workshop.qmd
               text: Consolidate!  
          - text: ---
          - section: "Week 5"
            contents: 
             - href: r4babs2/week-5/overview.qmd
               text: About  
             - href: r4babs2/week-5/study_before_workshop.qmd
               text: Prepare! 
             - href: r4babs2/week-5/workshop.qmd
               text: Workshop
             - href: r4babs2/week-5/study_after_workshop.qmd
               text: Consolidate!  
          - text: ---
          - section: "Week 6"
            contents: 
             - href: r4babs2/week-6/overview.qmd
               text: About  
             - href: r4babs2/week-6/study_before_workshop.qmd
               text: Prepare! 
             - href: r4babs2/week-6/workshop.qmd
               text: Workshop
             - href: r4babs2/week-6/study_after_workshop.qmd
               text: Consolidate!  
execute:
  echo: true
  warning: false
  output: true
  error: true

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/3mmarand\.github\.io\/R4BABS'
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-link: true
    code-overflow: wrap
    code-line-numbers: false
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    
    author-meta: Emma Rand

bibliography: references.bib


editor: source

