---
title: "Workshop"
subtitle: "Data Analysis 3: Biomedical sciences - Your data analysis"
toc: true
toc-location: right
editor: 
  markdown: 
    wrap: sentence
---

```{r}
#| include: false
library(tidyverse)
library(kableExtra)
```

# Introduction

In this workshop you will use the tools you used in the previous 
workshop (and before!) to analyse the data you have collected.
You will provide some key pieces of information for the class data set.

# Exercises

## Getting started on your own analysis

🎬 Open the RStudio Project you created in the [Consolidation exercise from week 2](../week-2/study_after_workshop.html).

🎬 If you have not already done so, save your data files to the project.
Are the file names going to be easy for you to work with?
[Remember](../week-2/workshop.html#make-data-easier-to-work-with) that 
we used the file names to label to rows with their treatment (Media, 
LPS or ECOLIGreen) and antibody (ISOTYPE or TNFAPC) so if you do not 
match the names you will need to redesign the code appropriately. It is 
easier to rename your files!

🎬 Open your R script and begin to analyse your data.


🎬 Use `ggsave()` to write plots you might use in your report to file.
You will learn how to produce a variety of other plots in Week 6



## Data for the class dataset.

You need to provide the following information for the class dataset:

-   group_name A name for your group. Take care not to use a name used
    by others. Take care to use the exactly the same name for each of 
    your rows

-   `cell_treatment`One of MEDIA, LPS or ECOLIGreen 

-   `antibody` One of ISOTYPE or TNFAPC

-   `n` The number of cells in sample after flowAI cleaning

-   `n_live` The number of cells in sample after flowAI cleaning *and* 
     removing dead cells/debris ("gating") (*i.e.*, the % live cells)

-   `perc_live` The % of cells in sample after flowAI cleaning *and* 
     removing dead cells/debris ("gating") (*i.e.*, the % live cells)

-   `apc_cut` threshold for logicle transformed TNFa_APC_Lin. This 
     should be the *same* for all your samples and indicates the level 
     at which cells are postive for TNF-α positive

-   `mean_apc` Mean fluorescence intensity of the logicle transformed 
     TNFa_APC_Lin in the TNF-α positive cells

-   `n_pos_tnfa` Number of TNF-α positive cells

-   `perc_pos_tnfa` Percent of live cells that are TNF-α positive

Enter these in the [BIO00066I Biomedical Sciences class data]()

Some columns are required for the class analysis.
Other columns help you get to the required values and help others 
determine the reliability of your data.

## How to change the name of an RStudio project.

You will need to rename your RStudio Project to your exam number 
before you submit. You can change the name of an RStudio project by:

-   closing the project

-   renaming both the project folder and the `.Rproj` file.

# Independent study following the workshop

[Consolidate](study_after_workshop.qmd)

# The Code file

This contains all the code needed in the workshop even where it is not visible on the webpage.

The `workshop.qmd` file is the file I use to compile the practical.
Qmd stands for Quarto markdown.
It allows code and ordinary text to be interweaved to produce well-formatted reports including webpages.
[View the Qmd in Browser](https://github.com/3mmaRand/R4BABS/blob/main/r4babs4/week-4/workshop.qmd).
Coding and thinking answers are marked with `#---CODING ANSWER---` and `#---THINKING ANSWER---`

Pages made with R [@R-core], Quarto [@allaire2022], `knitr` [@knitr1; @knitr2; @knitr3], `kableExtra` [@kableExtra]

# References
