---
title: "Overview"
subitle: "Introduction to statistical models: Single linear regression"
toc: true
toc-location: right
---

This week, you'll learn about statistical *models*, which are
mathematical representations of data relationships. Specifically, you'll
explore the *general linear model (GLM)*, a broad framework for
analyzing data patterns.

Your first GLM will be *simple linear regression*, which fits a straight
line to data to predict a *response variable* (outcome) based on an
*explanatory variable* (predictor). We'll examine the two key
*parameters* estimated in this model: the *slope* (which shows how the
predictor influences the outcome) and the *intercept* (the value when
the predictor is zero). We'll also assess whether these values are
significantly different from zero.

### Learning objectives

The successful student will be able to:

-   explain what is meant by a statistical model and fitting a model

-   know what the general linear model is and how it relates to
    regression

-   explain the principle of regression and know when it can be applied

-   apply and interpret a simple linear regression in R

-   evaluate whether the assumptions of regression are met

-   scientifically report a regression result including appropriate
    figures

### Instructions

1.  [Prepare](study_before_workshop.qmd)

    i.  📖 Read What is a statistical model
    ii. 📖 Read Single linear regression

2.  [Workshop](workshop.qmd)

    i.💻 Carry out a single linear regression

3.  [Consolidate](study_after_workshop.qmd)

    i.  💻 Appropriately analyse the relationship between juvenile
        hormone and mandible size in stage beetles
    ii. 💻 Appropriately analyse the relationship between anxiety and
        performance
