---
title: "Week 8: Types of variable, the normal distribution and summarising data"
---

The type of values our data can take is important in how we analyse and visualise it. This week you will learn the difference between continuous and discrete values and how we summarise and visualise them. You will also learn about the "normal distribution" which is the most important continuous distribution. 

### Learning objectives

The successful student will be able to:

-   distinguish between continuous, discrete, nominal and ordinal variable

-   read in data in to RStudio from a plain text file and Excel files

-   summarise and plot variables appropriately for the data type

### Instructions

1.  [Prepare](study_before_workshop.qmd)

    i.  📖 Read: Ideas about data

2.  [Workshop](workshop.qmd)

    i.  💻 Importing data
    
    ii. 💻 Summarising discrete data
    
    iii. 💻 Summarising count data
    
    iv. 💻 Summarising continuous data

3.  [Consolidate](study_after_workshop.qmd)

    i.  💻 Summarise some data

    ii. 💻 Plot some data
    
    iii. 💻 Format a plot (1)
    
    iv. 💻 Format a plot (2)
    
    v.  📖 Read Understanding the pipe `|>`
