---
title: "Overview"
subtitle: "Assessment introduction"
toc: true
toc-location: right
---

This week we will be looking at the assessment for this module and
introducing you to a specimen sample of the assessment so that you can
familiarise yourself with the format and what we are expecting you to
produce.  We will also look at the markingcriteria. This material can
also be found on the VLE under the module assessment marking criteria 
section. 

### Learning objectives

The successful student will be able to:

-   Understand the structure of the Rproject we will be expecting you to
    produce in the assessment (e.g. segregated into data-raw, figures
    etc).

-   Understand the marking criteria so you understand how the assessment
    is going to be evaluated 

-   Know where to look on the VLE for additional assessment information

-   Know the appropriate dates for the release and submisison of the
    assessment.

### Instructions

1.  [Prepare](study_before_workshop.qmd)

    i.  📖 Read the marking criteria available on the VLE

2.  [Workshop](workshop.qmd)

    i.  💻 Explore the specimen Rproject

3.  [Consolidate](study_after_workshop.qmd)

    i.  📖 Refamiliarise yourself with how Rprojects work
